config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#top'
  get 'about', to:'home#about'
  resources :users, only: [:show, :update, :edit]
  resources :gossips, only: [:new, :create, :index] do
    resources :chats, only: [:index, :create, :new] 
    namespace :api do
      resources :chats, only: :new, defaults: { format: 'json' }
    end
  end

  resources :movies do
    resources :comments, only: :create
  end
  get 'searchs', to: 'searchs#map'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :gossip
  belongs_to :user

  validates :content, presence: true, unless: :image?

  mount_uploader :image, ImageUploader

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :movie
  belongs_to :user
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  has_many :gossip_users
  has_many :users, through: :gossip_users
  has_many :chats
  validates :name, presence: true, uniqueness: true
end

app/models/gossip_user.rb
class GossipUser < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  has_many :comments

  validates :title, presence: true, unless: :image?
  validates :director, presence: true
  validates :summary, presence: true

  mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :gossip_users
  has_many :gossips, through: :gossip_users
  has_many :chats
  has_many :movies
  has_many :comments

  validates :name, presence: true, uniqueness: true

  mount_uploader :image, ImageUploader
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_gossip

  def index
    @chat = Chat.new
    @chats = @gossip.chats.includes(:user)
    @nums = @gossip.chats.count
  end

  def new
    @chat = Chat.new
    @chats = @gossip.chats.includes(:user)
  end

  def create
    @chat = @gossip.chats.new(chat_params)
    if @chat.save
      respond_to do |format|
        format.json
      end
    else
      @chats = @gossip.chats.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :new
    end
  end

  private

  def chat_params
    params.require(:chat).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_gossip
    @gossip = Gossip.find(params[:gossip_id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new
    Comment.create(comment_params)
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, movie_id: params[:movie_id])
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def new
    @gossip = Gossip.new
    @gossip.users << current_user
  end
  def create
    @gossip = Gossip.new(gossip_params)
    if @gossip.save
      redirect_to gossips_path, notice: 'ゴシップを作成しました'
    else
      render :new
    end
  end
  def index
    @gossips = Gossip.all.order("created_at DESC")
  end

  private
  def gossip_params
    params.require(:gossip).permit(:name, user_ids: [])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
  def about
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to movies_path, notice: 'movie情報が作成されました'
    else
      @movies = Movie.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :new
    end
  end

  def show
    @movie = Movie.find(params[:id])
    @comment = Comment.new
    @comments = @movie.comments.includes(:user)
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
      redirect_to movies_path(@movie.id)
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    if @movie.destroy
      redirect_to movies_path, notice: '削除しました'
    else
      @movie = Movie.includes(:user)
      render :edit
    end
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :summary, :director, :original, :actor, :image).merge(user_id: current_user.id)
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  def map
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/chitchats_helper.rb
module ChitchatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.haml
.comment_show
  .comment_show__wrapper
    .comment_show__wrapper__head
      あなたの声を投稿しました
    .comment_show__wrapper__links
      .comment_show__wrapper__links__top
        =link_to root_path do
          Topへ戻る
      .comment_show__wrapper__links__show
        =link_to movie_path(params[:movie_id]) do
          映画詳細へ
  

app/views/gossips/index.html.haml
.gossip_index
  .gossip_index__title
    %h1
      Gossip一覧
    .gossip_index__title__return
      =link_to root_path do
        Home
  .gossip_index__link
    = link_to new_gossip_path do
      gossip作成
  .gossip_index__wrapper
    .gossip_index__wrapper__side
      .gossip_index__wrapper__side__title
        Your Gossips
      .gossip_index__wrapper__side__contents
        -current_user.gossips.each do |gossip|
          .gossip_index__wrapper__side__contents__content
            .gossip_index__wrapper__side__contents__content__name
              = link_to gossip_chats_path(gossip.id) do
                = gossip.name
            .gossip_index__wrapper__side__contents__content__time
              = gossip.created_at.strftime("%Y年%m月%d日 %H時%M分")
    .gossip_index__wrapper__main
      .gossip_index__wrapper__main__title
        Social Gossips
      .gossip_index__wrapper__main__contents
        -@gossips.each do |gossip|
          .gossip_index__wrapper__main__contents__content
            .gossip_index__wrapper__main__contents__content__name
              = link_to gossip_chats_path(gossip.id) do
                = gossip.name
            .gossip_index__wrapper__main__contents__content__time
              = gossip.created_at.strftime("%Y年%m月%d日 %H時%M分")

app/views/gossips/new.html.haml
.gossip_new
  .gossip_new__title
    %h1
      Gossip作成
    .gossip_new__title__return
      =link_to root_path do
        Home
      =link_to gossips_path do
        GossipsTalk
  .gossip_new__wrapper
    .gossip_new__wrapper__effect
      .gossip_new__wrapper__effect__form
        = form_with model: @gossip, local: true do |f|
          .GossipForm_input
            = f.text_field :name, placeholder: "Gossipタイトルを入力してください"
          .GossipForm_check  
            = f.collection_check_boxes :user_ids, User.where(id: current_user.id), :id, :name
          .GossipForm_btn  
            = f.submit "作成"

app/views/users/edit.html.haml
.userShow
  .userShow__account
    .userShow__account__name
      = current_user.name
    .userShow__account__image
      -if current_user.image.present?
        = image_tag src= "#{current_user.image}"
      -else
        = image_tag src='ログイン素材.png'
    .userShow__account__logout
      = link_to "ログアウト", destroy_user_session_path, method: :delete

  %h1
    編集
  .userShow__updateForm
    = form_for(current_user) do |f|
      .updateFormIn
        .updateFormIn__Field
          = f.label :name
        .updateFormIn__input
          = f.text_field :name, autofocus: true
      .updateFormIn
        .updateFormIn__Field
          = f.label :email
        .updateFormIn__input
          = f.email_field :email
        .updateFormIn__Field
          = f.label :image
        .updateFormIn__input
          = f.file_field :image
      = f.submit "Update", class: 'UpdateButton'
  %a.returnTop(href="/")
    TOPへ戻る

-# .AccountPage
-#   .AccountPage__title
-#     %h2 Edit Account
-#     %h5 アカウントの編集
-#     = link_to "ログアウト", '#', class: 'Button'
-#     = link_to "トップページに戻る", :back, class: 'Button'
-#   .AccountPage__form
-#     = form_for(current_user) do |f|
-#       .FormField
-#         .FormField__label--normal
-#           = f.label :name
-#         .FormField__input--normal
-#           = f.text_field :name, autofocus: true
-#       .FormField
-#         .FormField__label--normal
-#           = f.label :email
-#         .FormField__input--normal
-#           = f.email_field :email
-#       = f.submit "Update", class: 'Button UserButton'

app/views/users/show.html.haml
.userShow
  .userShow__account
    .userShow__account__name
      = current_user.name
    .userShow__account__image
      = image_tag src= "#{current_user.image}"


  .userShow__updateForm
    = form_for(current_user) do |f|
      .updateFormIn
        .updateFormIn__Field
          = f.label :name
        .updateFormIn__input
          = f.text_field :name, autofocus: true
      .updateFormIn
        .updateFormIn__Field
          = f.label :email
        .updateFormIn__input
          = f.email_field :email
        .updateFormIn__Field
          = f.label :image
        .updateFormIn__input
          = f.file_field :image
      = f.submit "Update", class: 'UpdateButton'
  %a.returnTop(href="/")
    TOPへ戻る