config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#top'
  get 'about', to:'home#about'
  resources :users, only: [:show, :update, :edit]
  resources :gossips, only: [:new, :create, :index] do
    resources :chats, only: [:index, :create, :new] 
    namespace :api do
      resources :chats, only: :new, defaults: { format: 'json' }
    end
  end

  resources :movies do
    resources :comments, only: :create
  end
  get 'searchs', to: 'searchs#map'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :gossip
  belongs_to :user

  validates :content, presence: true, unless: :image?

  mount_uploader :image, ImageUploader

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :movie
  belongs_to :user
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  has_many :gossip_users
  has_many :users, through: :gossip_users
  has_many :chats
  validates :name, presence: true, uniqueness: true
end

app/models/gossip_user.rb
class GossipUser < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  has_many :comments

  validates :title, presence: true, unless: :image?
  validates :director, presence: true
  validates :summary, presence: true

  mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :gossip_users
  has_many :gossips, through: :gossip_users
  has_many :chats
  has_many :movies
  has_many :comments

  validates :name, presence: true, uniqueness: true

  mount_uploader :image, ImageUploader
end

app/controllers/api/chats_controller.rb
class Api::ChatsController < ApplicationController
  before_action :set_gossip

  def new
    # ルーティングでの設定によりparamsの中にgroup_idというキーでグループのidが入るので、これを元にDBからグループを取得する
    gossip = Gossip.find(params[:gossip_id])
    # ajaxで送られてくる最後のメッセージのid番号を変数に代入
    last_chat_id = params[:id].to_i
    # 取得したグループでのメッセージ達から、idがlast_message_idよりも新しい(大きい)メッセージ達のみを取得
    @chats = @gossip.chats.includes(:user).where("id > ?", last_chat_id)
  end

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_gossip

  def index
    @chat = Chat.new
    @chats = @gossip.chats.includes(:user)
    @nums = @gossip.chats.count
  end

  def new
    @chat = Chat.new
    @chats = @gossip.chats.includes(:user)
  end

  def create
    @chat = @gossip.chats.new(chat_params)
    if @chat.save
      respond_to do |format|
        format.json
      end
    else
      @chats = @gossip.chats.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :new
    end
  end

  private

  def chat_params
    params.require(:chat).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_gossip
    @gossip = Gossip.find(params[:gossip_id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new
    Comment.create(comment_params)
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, movie_id: params[:movie_id])
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def new
    @gossip = Gossip.new
    @gossip.users << current_user
  end
  def create
    @gossip = Gossip.new(gossip_params)
    if @gossip.save
      redirect_to gossips_path, notice: 'ゴシップを作成しました'
    else
      render :new
    end
  end
  def index
    @gossips = Gossip.all.order("created_at DESC")
  end

  private
  def gossip_params
    params.require(:gossip).permit(:name, user_ids: [])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
  def about
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to movies_path, notice: 'movie情報が作成されました'
    else
      @movies = Movie.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :new
    end
  end

  def show
    @movie = Movie.find(params[:id])
    @comment = Comment.new
    @comments = @movie.comments.includes(:user)
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
      redirect_to movies_path(@movie.id)
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    if @movie.destroy
      redirect_to movies_path, notice: '削除しました'
    else
      @movie = Movie.includes(:user)
      render :edit
    end
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :summary, :director, :original, :actor, :image).merge(user_id: current_user.id)
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  def map
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/chitchats_helper.rb
module ChitchatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chats/index.html.haml
.chat_index
  .chat_index__title
    = @gossip.name
    .chat_index__title__links
      =link_to root_path do
        Home
      = link_to gossips_path do
        Gossips一覧
  .chat_index__wrapper
    .chat_index__wrapper__contents
      - @chats.each do |chat|
        .chat
          .chat__in
            .chat__in__left
              .chat__in__left__userIcon
                = image_tag src= "#{chat.user.image}"
            .chat__in__right
              .chat__in__right__top
                .chat__in__right__top__userName
                  = chat.user.name
                .chat__in__right__top__createdTime
                  = chat.created_at.strftime("%Y年%m月%d日 %H時%M分")
              .chat__in__right__bottom
                .chat__in__right__bottom__content
                  = chat.content
                  = image_tag chat.image.url, class: 'Message__image' if chat.image.present?
  .chat_index__btn
    = link_to new_gossip_chat_path(@gossip.id)  do
      .chat_index__btn__left
        =@nums
      .chat_index__btn__right
        投稿する

app/views/chats/new.html.haml
= javascript_include_tag 'autoReload'
.chat_new
  .chat_new__title
    = @gossip.name
    .chat_new__title__links
      =link_to root_path do
        Home
      = link_to gossip_chats_path(@gossip.id) do
        Chat一覧
  .chat_new__wrapper
    .chat_new__wrapper__chatsIndex
      - @chats.each do |chat|
        .chat{data: {chat: {id: chat.id}}}
          .chat__in
            .chat__in__left
              .chat__in__left__userIcon
                = image_tag src= "#{chat.user.image}"
            .chat__in__right
              .chat__in__right__top
                .chat__in__right__top__userName
                  = chat.user.name
                .chat__in__right__top__createdTime
                  = chat.created_at.strftime("%Y年%m月%d日 %H時%M分")
              .chat__in__right__bottom
                .chat__in__right__bottom__content
                  = chat.content
                  = image_tag chat.image.url, class: 'Message__image' if chat.image.present?
    .chat_new__wrapper__contents
      %p
        メッセージ作成
      .chat_new__wrapper__contents__user
        %p
          %span 
            作成者
          = current_user.name
      .chat_new__wrapper__contents__form
        = form_with model: [@gossip, @chat], html: {class: "Form"}, local: true do |f|
          .formContents
            = f.text_area :content, class: 'Form__inputContent', placeholder: 'type a message'
            = f.label :image, class: 'Form__inputImage' do
              = icon('far', 'image', class: 'Form__icon')
              = f.file_field :image, class: 'Hidden'
          .formBtn
            = f.submit 'Chat', class: 'Form__submit'
            = icon('fas', 'hand-point-left')